# service overview
apiVersion: v1
kind: Service
metadata:
  name: tokengen
  labels:
    app: web
spec:
  type:  NodePort
  selector:
    app: web
  ports:   
  - name: http   
    port: 80
    targetPort: 5000
    nodePort: 30200