apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accounting-pvc
  labels:
    type: aws-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: aws-gp2
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: "aws-pv"