apiVersion: v1
kind: PersistentVolume
metadata:
  name: accounting-pv
  labels:
    type: aws-pv
spec:
  accessModes:
   - ReadWriteOnce
  storageClassName: aws-gp2   
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain   
  awsElasticBlockStore:
    volumeID: vol-01c51548952e08c6c