# simple pod to deploy .net core web api app container
apiVersion: v1
kind: Pod
metadata:
  name: tokengen
  labels:
    app: web
spec:
  containers:    
  - name: tokengen-ctr
    image: jawadhasanshani/dotnettokengen
    ports:
     - containerPort: 5000     